### PR TITLE
Support for `UNet3DConditionModel`

### PR DESCRIPTION
**Pull request by neurowelt**
Thank you so much for this repository! As I am currently working with both image and video pipelines, I added the UNet 3D regsiter methods, so you could use FreeU in Zeroscope/Modelscope models.

### Changelog:
- Add `UpBlock3D` and `CrossAttnUpBlock3D` register methods
- Add `scale` argument required for newer `diffusers` versions (tested on v.0.21.2)
- Cosmetics, added method descriptions, improved logging and cleaned up imports

### CODE REVIEW

**Comment by charlesmccarthy** [comment]
Amazing please join us on the t2v and zeroscope discord https://discord.gg/hQEjvgRQkY

**Comment by YisuiTT** [comment]
> Thank you so much for this repository! As I am currently working with both image and video pipelines, I added the UNet 3D regsiter methods, so you could use FreeU in Zeroscope/Modelscope models.
> 
> ### Changelog:
> * Add `UpBlock3D` and `CrossAttnUpBlock3D` register methods
> * Add `scale` argument required for newer `diffusers` versions (tested on v.0.21.2)
> * Cosmetics, added method descriptions, improved logging and cleaned up imports

Hello, I use this code in animatediff, but there is an error：TypeError: register_free_upblock3d.<locals>.up_forward.<locals>.forward() got an unexpected keyword argument 'encoder_hidden_states'

**Comment by neurowelt** [comment]
@YisuiTT Could you provide a bit more context - which AnimateDiff are you using and how do you register the FreeU blocks?

**Comment by YisuiTT** [comment]
Thanks for answer. I use this AnimateDiff：https://github.com/tumurzakov/AnimateDiff, and add FreeU like this: 
image

the whole error：

**Comment by neurowelt** [comment]
Thanks for the traceback @YisuiTT , I'll try to reproduce it and will let know when I figure it out 🤗

**Comment by neurowelt** [comment]
@YisuiTT Sorry for not checking this out for such a long time, it was a bit hectic for me. I think you should check out the newest `diffusers` update, it contains a lot of things including [AnimateDiff](https://github.com/huggingface/diffusers/pull/5413) and [FreeU](https://github.com/huggingface/diffusers/pull/5164).

You can check out the detailed changelog [here](https://github.com/huggingface/diffusers/releases/tag/v0.22.0).

**Comment by YisuiTT** [comment]
🆗, thanks for telling me.

**Pull request merged**
